services:
  note_in_book_mysql:
    container_name: mysql
    image: mysql:8.0
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: NoteInBookDb
      MYSQL_ROOT_PASSWORD: 12345678
  
  elasticsearch:
    image: elasticsearch:8.16.2
    container_name: elasticsearch
    ports:
      - "9200:9200"
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    networks:
      - elk

  kibana:
    image: kibana:8.16.2
    container_name: kibana
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    ports:
      - '5601:5601'
    depends_on:
      - elasticsearch
    networks:
      - elk

networks:
  elk:
    driver: bridge